interface Instrument {
    number: number,
    id: string,
    name: string,
}

const instruments: Instrument[] = [
    {number: 0, id: 'standard kit', name: ''},
    {number: 1, id: 'acoustic grand piano', name: 'piano'},
    {number: 2, id: 'bright acoustic piano', name: 'piano'},
    {number: 3, id: 'electric grand piano', name: 'piano'},
    {number: 4, id: 'honky-tonk piano', name: 'piano'},
    {number: 5, id: 'electric piano 1', name: 'piano'},
    {number: 6, id: 'electric piano 2', name: 'piano'},
    {number: 7, id: 'harpsichord', name: 'piano'},
    {number: 8, id: 'clavi', name: 'piano'},

    {number: 9, id: 'celesta', name: 'xylophone'},
    {number: 10, id: 'glockenspiel', name: 'xylophone'},
    {number: 11, id: 'music box', name: 'xylophone'},
    {number: 12, id: 'vibraphone', name: 'xylophone'},
    {number: 13, id: 'marimba', name: 'xylophone'},
    {number: 14, id: 'xylophone', name: 'xylophone'},
    {number: 15, id: 'tubular bells', name: 'xylophone'},
    {number: 16, id: 'dulcimer', name: 'xylophone'},

    {number: 17, id: 'drawbar organ', name: 'organ'},
    {number: 18, id: 'percussive organ', name: 'organ'},
    {number: 19, id: 'rock organ', name: 'organ'},
    {number: 20, id: 'church organ', name: 'organ'},
    {number: 21, id: 'reed organ', name: 'organ'},

    {number: 22, id: 'accordion', name: 'harmonium'},
    {number: 23, id: 'harmonica', name: 'harmonium'},
    {number: 24, id: 'tango accordion', name: 'harmonium'},

    {number: 25, id: 'acoustic guitar (nylon)', name: 'guitar-nylon'},
    {number: 26, id: 'acoustic guitar (steel)', name: 'guitar-acoustic'},
    {number: 27, id: 'electric guitar (jazz)', name: 'guitar-electric'},
    {number: 28, id: 'electric guitar (clean)', name: 'guitar-electric'},
    {number: 29, id: 'electric guitar (muted)', name: 'guitar-electric'},
    {number: 30, id: 'overdriven guitar', name: 'guitar-electric'},
    {number: 31, id: 'distortion guitar', name: 'guitar-electric'},
    {number: 32, id: 'guitar harmonics', name: 'guitar-electric'},

    {number: 33, id: 'acoustic bass', name: 'bass-electric'},
    {number: 34, id: 'electric bass (finger)', name: 'bass-electric'},
    {number: 35, id: 'electric bass (pick)', name: 'bass-electric'},
    {number: 36, id: 'fretless Bass', name: 'bass-electric'},
    {number: 37, id: 'slap bass 1', name: 'bass-electric'},
    {number: 38, id: 'slap bass 2', name: 'bass-electric'},
    {number: 39, id: 'synth bass 1', name: 'bass-electric'},
    {number: 40, id: 'synth bass 2', name: 'bass-electric'},

    {number: 41, id: 'violin', name: 'violin'},
    {number: 42, id: 'viola', name: 'violin'},
    {number: 43, id: 'cello', name: 'cello'},
    {number: 44, id: 'contrabass', name: 'contrabass'},
    {number: 45, id: 'tremolo strings', name: 'violin'},
    {number: 46, id: 'pizzicato strings', name: 'violin'},
    {number: 47, id: 'orchestral harp', name: 'harp'},
    {number: 48, id: 'timpani', name: ''},

    {number: 49, id: 'string ensemble 1', name: 'violin'},
    {number: 50, id: 'string ensemble 1', name: 'violin'},
    {number: 51, id: 'synth strings 1', name: 'violin'},
    {number: 52, id: 'synth strings 2', name: 'violin'},
    {number: 53, id: 'choir aahs', name: 'saxophone'},
    {number: 54, id: 'voice oohs', name: 'saxophone'},
    {number: 55, id: 'synth voice', name: 'saxophone'},
    {number: 56, id: 'orchestra hit', name: ''},

    {number: 57, id: 'trumpet', name: 'trumpet'},
    {number: 58, id: 'trombone', name: 'trombone'},
    {number: 59, id: 'tuba', name: 'tuba'},
    {number: 60, id: 'muted trumpet', name: 'trumpet'},
    {number: 61, id: 'french horn', name: 'french-horn'},
    {number: 62, id: 'brass section', name: 'french-horn'},
    {number: 63, id: 'synth brass 1', name: 'trumpet'},
    {number: 64, id: 'synth brass 2', name: 'trumpet'},

    {number: 65, id: 'soprano sax', name: 'saxophone'},
    {number: 66, id: 'alto sax', name: 'saxophone'},
    {number: 67, id: 'tenor sax', name: 'saxophone'},
    {number: 68, id: 'baritone sax', name: 'saxophone'},
    {number: 69, id: 'oboe', name: 'saxophone'},
    {number: 70, id: 'english horn', name: 'french-horn'},
    {number: 71, id: 'bassoon', name: 'bassoon'},
    {number: 72, id: 'clarinet', name: 'clarinet'},

    {number: 73, id: 'piccolo', name: 'flute'},
    {number: 74, id: 'flute', name: 'flute'},
    {number: 75, id: 'recorder', name: 'flute'},
    {number: 76, id: 'pan flute', name: 'flute'},
    {number: 77, id: 'blown bottle', name: 'flute'},
    {number: 78, id: 'shakuhachi', name: 'flute'},
    {number: 79, id: 'whistle', name: 'flute'},
    {number: 80, id: 'ocarina', name: 'flute'},

    {number: 81, id: 'lead 1 (square)', name: 'piano'},
    {number: 82, id: 'lead 2 (sawtooth)', name: 'piano'},
    {number: 83, id: 'lead 3 (calliope)', name: 'piano'},
    {number: 84, id: 'lead 4 (chiff)', name: 'piano'},
    {number: 85, id: 'lead 5 (charang)', name: 'piano'},
    {number: 86, id: 'lead 6 (voice)', name: 'piano'},
    {number: 87, id: 'lead 7 (fifths)', name: 'piano'},
    {number: 88, id: 'lead 8 (bass + lead)', name: 'piano'},
]

export {instruments}